Added attestation for julia
docker-library/julia pull request #86
Opened 2023-10-25 18:50 UTC by LaurentGoderre

2023-11-10 00:34 UTC, yosifkit requested changes

2023-11-10 00:34 UTC, yosifkit commented on apply-templates.sh
> +	wget -qO "$jqf" 'https://github.com/docker-library/bashbrew/raw/master/scripts/template-helper-functions.jq'
The download of `.template-helper-functions.jq` should use a specific commit like the awk script does. This'll help each repo control when it brings in improvements/changes.

2023-11-10 00:34 UTC, yosifkit commented on apply-templates.sh
> +
```suggestion
```
Extra empty line.

2023-11-10 00:34 UTC, yosifkit commented on Dockerfile-linux.template
> +
```suggestion
```
Extra empty line.

2023-11-10 15:27 UTC, LaurentGoderre commented
Done

2023-11-14 01:16 UTC, yosifkit approved these changes

2023-11-14 01:24 UTC, merged